name: tests

on:
  pull_request:
    branches:
      - "18.0*"
  push:
    branches:
      - "18.0"

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ghcr.io/oca/oca-ci/py3.10-odoo18.0:latest
    name: test with Odoo 18.0
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    env:
      OCA_ENABLE_CHECKLOG_ODOO: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Install addons and dependencies
        run: oca_install_addons
      - name: Initialize test db
        run: oca_init_test_database
      - name: Run tests
        run: oca_run_tests
